import type { Metadata } from "next";
import "./globals.css";
import { dmSans, paytoneOne } from "./fonts"; 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dmSans.variable} ${paytoneOne.variable}`}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
